-- Production analysis for ModernBERT v6 framing scores.
-- Source scores: 29,695,839 unique people.

USE DATABASE PDL_CLEAN;
USE SCHEMA BGI_2026_05;

-- A reusable person-level analytic base. This preserves the raw score table.
CREATE OR REPLACE TABLE FRAMING_ANALYSIS_PERSON AS
SELECT
    s.PERSON_ID,
    s.ENSEMBLE_PROB,
    s.LABEL,
    p.JOB_TITLE,
    p.JOB_TITLE_ROLE,
    p.JOB_TITLE_SUB_ROLE,
    p.JOB_TITLE_CLASS,
    p.JOB_ONET_CODE,
    p.JOB_ONET_MAJOR_GROUP,
    p.JOB_ONET_MINOR_GROUP,
    p.JOB_ONET_BROAD_OCCUPATION,
    p.JOB_ONET_SPECIFIC_OCCUPATION,
    p.INDUSTRY,
    p.JOB_COMPANY_INDUSTRY,
    p.JOB_COMPANY_NAME,
    p.JOB_COMPANY_TYPE,
    p.JOB_COMPANY_SIZE,
    p.BGI_STATE,
    p.BGI_CBSA_NAME,
    p.SEX,
    p.BGI_RACE,
    p.BIRTH_YEAR
FROM FRAMING_SCORES_V6_SEED123 s
JOIN ROOT_PERSON p USING (PERSON_ID);

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_OVERALL AS
SELECT
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    APPROX_PERCENTILE(ENSEMBLE_PROB, 0.10) AS P10_PROB,
    APPROX_PERCENTILE(ENSEMBLE_PROB, 0.90) AS P90_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON;

-- Standard aggregate schema used by every categorical breakdown.
CREATE OR REPLACE TABLE FRAMING_ANALYSIS_OCCUPATION AS
SELECT
    JOB_ONET_SPECIFIC_OCCUPATION AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE JOB_ONET_SPECIFIC_OCCUPATION IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 500
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_OCCUPATION_BROAD AS
SELECT
    JOB_ONET_BROAD_OCCUPATION AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE JOB_ONET_BROAD_OCCUPATION IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_INDUSTRY AS
SELECT
    COALESCE(JOB_COMPANY_INDUSTRY, INDUSTRY) AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE COALESCE(JOB_COMPANY_INDUSTRY, INDUSTRY) IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_COMPANY_TYPE AS
SELECT
    JOB_COMPANY_TYPE AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE JOB_COMPANY_TYPE IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_STATE AS
SELECT
    BGI_STATE AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE BGI_STATE IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_METRO AS
SELECT
    BGI_CBSA_NAME AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE BGI_CBSA_NAME IS NOT NULL
GROUP BY 1
HAVING COUNT(*) >= 5000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_DEMOGRAPHICS AS
SELECT
    'SEX' AS DIMENSION,
    SEX AS GROUP_NAME,
    COUNT(*) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_PERSON
WHERE SEX IS NOT NULL
GROUP BY 1, 2
UNION ALL
SELECT
    'RACE',
    BGI_RACE,
    COUNT(*),
    AVG(ENSEMBLE_PROB),
    MEDIAN(ENSEMBLE_PROB),
    AVG(LABEL)
FROM FRAMING_ANALYSIS_PERSON
WHERE BGI_RACE IS NOT NULL
GROUP BY 1, 2;

-- EDUCATION can contain several records per person. Deduplicate each
-- person/school/degree/major combination before calculating group statistics.
CREATE OR REPLACE TABLE FRAMING_ANALYSIS_EDUCATION AS
SELECT DISTINCT
    s.PERSON_ID,
    s.ENSEMBLE_PROB,
    s.LABEL,
    e.BGI_SCHOOL_NAME,
    e.BGI_DEGREE,
    e.BGI_MAJOR_CIP4_NAME,
    e.BGI_MAJOR_CIP6_CODE,
    e.BGI_SUB_SCHOOL_TYPE,
    e.IPEDS_SCHOOL_SIZE,
    e.IPEDS_HIGHEST_LEVEL_OFFERED
FROM FRAMING_SCORES_V6_SEED123 s
JOIN EDUCATION e USING (PERSON_ID);

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_COLLEGE AS
SELECT
    BGI_SCHOOL_NAME AS GROUP_NAME,
    COUNT(DISTINCT PERSON_ID) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_EDUCATION
WHERE BGI_SCHOOL_NAME IS NOT NULL
GROUP BY 1
HAVING COUNT(DISTINCT PERSON_ID) >= 500
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_DEGREE AS
SELECT
    BGI_DEGREE AS GROUP_NAME,
    COUNT(DISTINCT PERSON_ID) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_EDUCATION
WHERE BGI_DEGREE IS NOT NULL
GROUP BY 1
HAVING COUNT(DISTINCT PERSON_ID) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

CREATE OR REPLACE TABLE FRAMING_ANALYSIS_MAJOR AS
SELECT
    BGI_MAJOR_CIP4_NAME AS GROUP_NAME,
    COUNT(DISTINCT PERSON_ID) AS N,
    AVG(ENSEMBLE_PROB) AS AVG_PROB,
    MEDIAN(ENSEMBLE_PROB) AS MEDIAN_PROB,
    AVG(LABEL) AS POSITIVE_SHARE
FROM FRAMING_ANALYSIS_EDUCATION
WHERE BGI_MAJOR_CIP4_NAME IS NOT NULL
GROUP BY 1
HAVING COUNT(DISTINCT PERSON_ID) >= 1000
ORDER BY POSITIVE_SHARE DESC, N DESC;

-- Headline views after execution.
SELECT * FROM FRAMING_ANALYSIS_OVERALL;
SELECT * FROM FRAMING_ANALYSIS_OCCUPATION ORDER BY POSITIVE_SHARE DESC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_OCCUPATION ORDER BY POSITIVE_SHARE ASC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_INDUSTRY ORDER BY POSITIVE_SHARE DESC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_INDUSTRY ORDER BY POSITIVE_SHARE ASC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_COLLEGE ORDER BY POSITIVE_SHARE DESC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_COLLEGE ORDER BY POSITIVE_SHARE ASC LIMIT 25;
SELECT * FROM FRAMING_ANALYSIS_DEGREE ORDER BY POSITIVE_SHARE DESC;
SELECT * FROM FRAMING_ANALYSIS_MAJOR ORDER BY POSITIVE_SHARE DESC LIMIT 25;
