USE DATABASE PDL_CLEAN;
USE SCHEMA BGI_2026_05;

-- Overall model output.
SELECT * FROM FRAMING_ANALYSIS_OVERALL;

-- Liberal-arts-college comparison by selectivity.
SELECT *
FROM SOCIETAL_GOOD_LIBERAL_ARTS_BY_SELECTIVITY
ORDER BY SELECTIVITY_LABEL, LIBERAL_ARTS;

-- Highest-scoring occupations with a meaningful sample size.
SELECT GROUP_NAME, N, POSITIVE_SHARE
FROM FRAMING_ANALYSIS_OCCUPATION
WHERE N >= 5000
ORDER BY POSITIVE_SHARE DESC
LIMIT 25;

-- Available published aggregate datasets.
SELECT *
FROM SOCIETAL_GOOD_DATASETS
ORDER BY DATASET_NAME;
